# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('POS', models.CharField(max_length=100)),
                ('dep', models.CharField(max_length=100)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.Word')),
                ('sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Sentence')),
            ],
        ),
        migrations.CreateModel(
            name='WordOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('color_class', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('chunk_no', models.IntegerField(default=0)),
                ('lemma', models.CharField(max_length=100)),
                ('pre_verb', models.CharField(max_length=100)),
                ('morph', models.CharField(max_length=100)),
                ('colspan', models.IntegerField(default=0)),
                ('wordlength', models.IntegerField(default=0)),
                ('aux_info', models.CharField(max_length=100)),
                ('sandhi_indexs', models.CharField(max_length=100)),
                ('sandhi_words', models.CharField(max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Word')),
            ],
        ),
    ]
