# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='wordID',
            field=models.IntegerField(default=0),
        ),
    ]
