# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_word_wordid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='head',
        ),
    ]
