# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_remove_word_head'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set([('sent', 'wordID')]),
        ),
    ]
