# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_auto_20180106_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordoption',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.Word'),
        ),
    ]
