# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0005_auto_20180106_1738'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordoption',
            unique_together=set([('word', 'level', 'color_class', 'position', 'chunk_no', 'lemma', 'pre_verb', 'morph', 'colspan', 'wordlength', 'aux_info', 'sandhi_indexs', 'sandhi_words')]),
        ),
    ]
