# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0007_auto_20180106_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='head',
            field=models.IntegerField(default=0),
        ),
    ]
