# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0008_word_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordoption',
            name='sandhi_words',
            field=models.CharField(max_length=300),
        ),
    ]
